// Comprehensive Categorized Food Database with Average Calories, Portions & Macros

export type FoodCategory =
  | "All"
  | "Breakfast"
  | "South Indian"
  | "North Indian"
  | "Breads & Rice"
  | "Curries & Dals"
  | "Meat & Seafood"
  | "Dairy & Eggs"
  | "Snacks & Fast Food"
  | "Fruits & Veggies"
  | "Beverages"
  | "High Protein";

export interface FoodDefinition {
  id: string;
  name: string;
  category: FoodCategory;
  brand?: string;
  calories: number; // average kcal for standard serving
  unit: string;     // e.g. "piece (40 g)", "bowl (150 g)", "plate (250 g)"
  grams: number;
  carbs: number;
  fat: number;
  protein: number;
  satFat: number;
  cholesterol: number;
  sodium: number;
  fibre: number;
  sugars: number;
  vitaminA: number;
  vitaminC: number;
  calcium: number;
  iron: number;
  potassium: number;
}

export const FOOD_CATEGORIES: FoodCategory[] = [
  "All",
  "Breakfast",
  "South Indian",
  "North Indian",
  "Breads & Rice",
  "Curries & Dals",
  "Meat & Seafood",
  "Dairy & Eggs",
  "Snacks & Fast Food",
  "Fruits & Veggies",
  "Beverages",
  "High Protein",
];

export const FOOD_DATABASE: FoodDefinition[] = [
  // ─── SOUTH INDIAN ───
  {
    id: "idli_std",
    name: "Idli",
    category: "South Indian",
    calories: 40,
    unit: "piece (30 g)",
    grams: 30,
    carbs: 7.8,
    fat: 0.1,
    protein: 2.0,
    satFat: 0,
    cholesterol: 0,
    sodium: 65,
    fibre: 0.4,
    sugars: 0.1,
    vitaminA: 0,
    vitaminC: 0,
    calcium: 5,
    iron: 0.5,
    potassium: 35,
  },
  {
    id: "masala_dosa",
    name: "Masala Dosa",
    category: "South Indian",
    calories: 250,
    unit: "piece (150 g)",
    grams: 150,
    carbs: 35.0,
    fat: 9.5,
    protein: 5.5,
    satFat: 2.0,
    cholesterol: 0,
    sodium: 420,
    fibre: 3.2,
    sugars: 1.2,
    vitaminA: 40,
    vitaminC: 5.0,
    calcium: 28,
    iron: 2.1,
    potassium: 190,
  },
  {
    id: "plain_dosa",
    name: "Plain Dosa",
    category: "South Indian",
    calories: 165,
    unit: "piece (100 g)",
    grams: 100,
    carbs: 28.5,
    fat: 4.2,
    protein: 3.8,
    satFat: 0.8,
    cholesterol: 0,
    sodium: 280,
    fibre: 1.8,
    sugars: 0.5,
    vitaminA: 10,
    vitaminC: 0.2,
    calcium: 20,
    iron: 1.4,
    potassium: 120,
  },
  {
    id: "medu_vada",
    name: "Medu Vada",
    category: "South Indian",
    calories: 135,
    unit: "piece (50 g)",
    grams: 50,
    carbs: 14.5,
    fat: 7.2,
    protein: 4.0,
    satFat: 1.5,
    cholesterol: 0,
    sodium: 210,
    fibre: 2.1,
    sugars: 0.2,
    vitaminA: 0,
    vitaminC: 0.5,
    calcium: 22,
    iron: 1.6,
    potassium: 140,
  },
  {
    id: "sambar",
    name: "Sambar",
    category: "South Indian",
    calories: 110,
    unit: "bowl (150 g)",
    grams: 150,
    carbs: 16.0,
    fat: 3.2,
    protein: 4.8,
    satFat: 0.5,
    cholesterol: 0,
    sodium: 480,
    fibre: 4.5,
    sugars: 3.0,
    vitaminA: 180,
    vitaminC: 8.0,
    calcium: 45,
    iron: 1.8,
    potassium: 260,
  },
  {
    id: "coconut_chutney",
    name: "Coconut Chutney",
    category: "South Indian",
    calories: 75,
    unit: "tbsp (30 g)",
    grams: 30,
    carbs: 2.4,
    fat: 7.0,
    protein: 0.9,
    satFat: 5.5,
    cholesterol: 0,
    sodium: 140,
    fibre: 1.5,
    sugars: 0.8,
    vitaminA: 5,
    vitaminC: 1.2,
    calcium: 8,
    iron: 0.6,
    potassium: 85,
  },
  {
    id: "upma",
    name: "Rava Upma",
    category: "South Indian",
    calories: 180,
    unit: "bowl (150 g)",
    grams: 150,
    carbs: 28.0,
    fat: 5.5,
    protein: 4.2,
    satFat: 1.0,
    cholesterol: 0,
    sodium: 320,
    fibre: 2.2,
    sugars: 1.0,
    vitaminA: 35,
    vitaminC: 3.0,
    calcium: 20,
    iron: 1.2,
    potassium: 110,
  },
  {
    id: "pongal",
    name: "Ven Pongal",
    category: "South Indian",
    calories: 220,
    unit: "bowl (150 g)",
    grams: 150,
    carbs: 32.0,
    fat: 7.8,
    protein: 6.0,
    satFat: 3.2,
    cholesterol: 10,
    sodium: 350,
    fibre: 2.8,
    sugars: 0.4,
    vitaminA: 50,
    vitaminC: 1.0,
    calcium: 30,
    iron: 1.9,
    potassium: 160,
  },

  // ─── BREADS & RICE ───
  {
    id: "chapati_std",
    name: "Chapati / Roti",
    category: "Breads & Rice",
    calories: 68,
    unit: "piece (40 g)",
    grams: 40,
    carbs: 14.2,
    fat: 0.4,
    protein: 2.6,
    satFat: 0.1,
    cholesterol: 0,
    sodium: 85,
    fibre: 2.1,
    sugars: 0.4,
    vitaminA: 0,
    vitaminC: 0,
    calcium: 12,
    iron: 1.1,
    potassium: 82,
  },
  {
    id: "butter_naan",
    name: "Butter Naan",
    category: "Breads & Rice",
    calories: 260,
    unit: "piece (90 g)",
    grams: 90,
    carbs: 42.0,
    fat: 7.8,
    protein: 6.5,
    satFat: 3.5,
    cholesterol: 15,
    sodium: 380,
    fibre: 1.8,
    sugars: 2.5,
    vitaminA: 60,
    vitaminC: 0,
    calcium: 38,
    iron: 2.2,
    potassium: 95,
  },
  {
    id: "white_rice",
    name: "Steamed White Rice",
    category: "Breads & Rice",
    calories: 130,
    unit: "bowl (100 g)",
    grams: 100,
    carbs: 28.2,
    fat: 0.3,
    protein: 2.7,
    satFat: 0.1,
    cholesterol: 0,
    sodium: 2,
    fibre: 0.4,
    sugars: 0.1,
    vitaminA: 0,
    vitaminC: 0,
    calcium: 10,
    iron: 0.8,
    potassium: 35,
  },
  {
    id: "brown_rice",
    name: "Brown Rice",
    category: "Breads & Rice",
    calories: 112,
    unit: "bowl (100 g)",
    grams: 100,
    carbs: 23.5,
    fat: 0.9,
    protein: 2.6,
    satFat: 0.2,
    cholesterol: 0,
    sodium: 5,
    fibre: 1.8,
    sugars: 0.2,
    vitaminA: 0,
    vitaminC: 0,
    calcium: 12,
    iron: 0.9,
    potassium: 79,
  },
  {
    id: "aloo_paratha",
    name: "Aloo Paratha",
    category: "Breads & Rice",
    calories: 290,
    unit: "piece (140 g)",
    grams: 140,
    carbs: 44.0,
    fat: 10.5,
    protein: 5.8,
    satFat: 3.2,
    cholesterol: 12,
    sodium: 460,
    fibre: 4.2,
    sugars: 1.5,
    vitaminA: 40,
    vitaminC: 9.5,
    calcium: 32,
    iron: 2.6,
    potassium: 310,
  },

  // ─── CURRIES & DALS ───
  {
    id: "dal_tadka",
    name: "Dal Tadka",
    category: "Curries & Dals",
    calories: 150,
    unit: "bowl (150 g)",
    grams: 150,
    carbs: 18.5,
    fat: 5.2,
    protein: 7.2,
    satFat: 1.2,
    cholesterol: 5,
    sodium: 380,
    fibre: 5.0,
    sugars: 1.2,
    vitaminA: 80,
    vitaminC: 4.0,
    calcium: 36,
    iron: 2.4,
    potassium: 290,
  },
  {
    id: "paneer_butter_masala",
    name: "Paneer Butter Masala",
    category: "Curries & Dals",
    calories: 320,
    unit: "bowl (200 g)",
    grams: 200,
    carbs: 14.0,
    fat: 24.0,
    protein: 12.0,
    satFat: 11.0,
    cholesterol: 45,
    sodium: 520,
    fibre: 2.8,
    sugars: 5.2,
    vitaminA: 280,
    vitaminC: 8.5,
    calcium: 260,
    iron: 1.8,
    potassium: 240,
  },
  {
    id: "palak_paneer",
    name: "Palak Paneer",
    category: "Curries & Dals",
    calories: 240,
    unit: "bowl (200 g)",
    grams: 200,
    carbs: 9.5,
    fat: 17.5,
    protein: 11.5,
    satFat: 7.8,
    cholesterol: 32,
    sodium: 460,
    fibre: 4.2,
    sugars: 2.5,
    vitaminA: 720,
    vitaminC: 18.0,
    calcium: 290,
    iron: 4.2,
    potassium: 410,
  },
  {
    id: "chole_masala",
    name: "Chole / Chana Masala",
    category: "Curries & Dals",
    calories: 220,
    unit: "bowl (180 g)",
    grams: 180,
    carbs: 32.0,
    fat: 6.5,
    protein: 9.0,
    satFat: 0.9,
    cholesterol: 0,
    sodium: 490,
    fibre: 7.5,
    sugars: 3.5,
    vitaminA: 110,
    vitaminC: 12.0,
    calcium: 75,
    iron: 3.8,
    potassium: 380,
  },
  {
    id: "rajma_curry",
    name: "Rajma Masala",
    category: "Curries & Dals",
    calories: 210,
    unit: "bowl (180 g)",
    grams: 180,
    carbs: 30.5,
    fat: 5.8,
    protein: 9.2,
    satFat: 0.8,
    cholesterol: 0,
    sodium: 470,
    fibre: 8.0,
    sugars: 2.8,
    vitaminA: 95,
    vitaminC: 10.0,
    calcium: 68,
    iron: 3.6,
    potassium: 420,
  },

  // ─── MEAT & SEAFOOD ───
  {
    id: "biryani_chicken",
    name: "Chicken Biryani",
    category: "Meat & Seafood",
    calories: 348,
    unit: "plate (250 g)",
    grams: 250,
    carbs: 42.0,
    fat: 12.0,
    protein: 18.0,
    satFat: 3.5,
    cholesterol: 45,
    sodium: 680,
    fibre: 2.2,
    sugars: 1.8,
    vitaminA: 60,
    vitaminC: 4.2,
    calcium: 35,
    iron: 2.5,
    potassium: 280,
  },
  {
    id: "mutton_biryani",
    name: "Mutton Biryani",
    category: "Meat & Seafood",
    calories: 420,
    unit: "plate (250 g)",
    grams: 250,
    carbs: 40.0,
    fat: 19.5,
    protein: 21.0,
    satFat: 7.2,
    cholesterol: 75,
    sodium: 720,
    fibre: 2.0,
    sugars: 1.5,
    vitaminA: 50,
    vitaminC: 3.5,
    calcium: 40,
    iron: 3.2,
    potassium: 310,
  },
  {
    id: "butter_chicken",
    name: "Butter Chicken",
    category: "Meat & Seafood",
    calories: 380,
    unit: "bowl (200 g)",
    grams: 200,
    carbs: 11.0,
    fat: 26.0,
    protein: 24.0,
    satFat: 12.5,
    cholesterol: 85,
    sodium: 610,
    fibre: 1.8,
    sugars: 4.8,
    vitaminA: 240,
    vitaminC: 6.0,
    calcium: 65,
    iron: 2.1,
    potassium: 340,
  },
  {
    id: "grilled_chicken_breast",
    name: "Grilled Chicken Breast",
    category: "High Protein",
    calories: 165,
    unit: "piece (100 g)",
    grams: 100,
    carbs: 0,
    fat: 3.6,
    protein: 31.0,
    satFat: 1.0,
    cholesterol: 85,
    sodium: 74,
    fibre: 0,
    sugars: 0,
    vitaminA: 15,
    vitaminC: 0,
    calcium: 15,
    iron: 1.0,
    potassium: 256,
  },
  {
    id: "fish_curry",
    name: "Fish Curry (South Indian)",
    category: "Meat & Seafood",
    calories: 210,
    unit: "bowl (180 g)",
    grams: 180,
    carbs: 6.5,
    fat: 9.8,
    protein: 22.0,
    satFat: 3.5,
    cholesterol: 55,
    sodium: 490,
    fibre: 1.6,
    sugars: 2.0,
    vitaminA: 120,
    vitaminC: 7.0,
    calcium: 50,
    iron: 1.8,
    potassium: 390,
  },

  // ─── DAIRY & EGGS ───
  {
    id: "boiled_egg",
    name: "Boiled Egg",
    category: "Dairy & Eggs",
    calories: 78,
    unit: "1 large (50 g)",
    grams: 50,
    carbs: 0.6,
    fat: 5.3,
    protein: 6.3,
    satFat: 1.6,
    cholesterol: 186,
    sodium: 62,
    fibre: 0,
    sugars: 0.6,
    vitaminA: 80,
    vitaminC: 0,
    calcium: 25,
    iron: 0.6,
    potassium: 63,
  },
  {
    id: "egg_omelette",
    name: "Egg Omelette (2 eggs)",
    category: "Dairy & Eggs",
    calories: 185,
    unit: "serving (120 g)",
    grams: 120,
    carbs: 2.2,
    fat: 14.2,
    protein: 12.5,
    satFat: 4.2,
    cholesterol: 370,
    sodium: 280,
    fibre: 0.5,
    sugars: 1.2,
    vitaminA: 180,
    vitaminC: 4.0,
    calcium: 60,
    iron: 1.8,
    potassium: 190,
  },
  {
    id: "curd_yogurt",
    name: "Plain Curd / Dahi",
    category: "Dairy & Eggs",
    calories: 98,
    unit: "bowl (150 g)",
    grams: 150,
    carbs: 7.0,
    fat: 4.5,
    protein: 5.5,
    satFat: 2.8,
    cholesterol: 18,
    sodium: 70,
    fibre: 0,
    sugars: 7.0,
    vitaminA: 45,
    vitaminC: 1.0,
    calcium: 180,
    iron: 0.2,
    potassium: 210,
  },
  {
    id: "paneer_raw",
    name: "Fresh Paneer",
    category: "High Protein",
    calories: 265,
    unit: "serving (100 g)",
    grams: 100,
    carbs: 3.5,
    fat: 20.8,
    protein: 18.3,
    satFat: 12.5,
    cholesterol: 48,
    sodium: 25,
    fibre: 0,
    sugars: 3.2,
    vitaminA: 210,
    vitaminC: 0,
    calcium: 480,
    iron: 0.5,
    potassium: 110,
  },

  // ─── BREAKFAST & CEREALS ───
  {
    id: "oatmeal_std",
    name: "Rolled Oatmeal with Milk",
    category: "Breakfast",
    calories: 190,
    unit: "bowl (200 g)",
    grams: 200,
    carbs: 32.0,
    fat: 4.2,
    protein: 7.5,
    satFat: 1.2,
    cholesterol: 5,
    sodium: 65,
    fibre: 4.0,
    sugars: 5.5,
    vitaminA: 50,
    vitaminC: 0,
    calcium: 140,
    iron: 1.9,
    potassium: 220,
  },
  {
    id: "poha",
    name: "Kanda Poha",
    category: "Breakfast",
    calories: 180,
    unit: "bowl (150 g)",
    grams: 150,
    carbs: 33.5,
    fat: 4.0,
    protein: 3.2,
    satFat: 0.6,
    cholesterol: 0,
    sodium: 290,
    fibre: 1.8,
    sugars: 1.8,
    vitaminA: 40,
    vitaminC: 8.5,
    calcium: 22,
    iron: 2.8,
    potassium: 130,
  },

  // ─── FRUITS & VEGGIES ───
  {
    id: "banana",
    name: "Banana",
    category: "Fruits & Veggies",
    calories: 105,
    unit: "1 medium (118 g)",
    grams: 118,
    carbs: 27.0,
    fat: 0.3,
    protein: 1.3,
    satFat: 0.1,
    cholesterol: 0,
    sodium: 1,
    fibre: 3.1,
    sugars: 14.4,
    vitaminA: 64,
    vitaminC: 10.3,
    calcium: 6,
    iron: 0.3,
    potassium: 422,
  },
  {
    id: "apple",
    name: "Apple",
    category: "Fruits & Veggies",
    calories: 95,
    unit: "1 medium (182 g)",
    grams: 182,
    carbs: 25.0,
    fat: 0.3,
    protein: 0.5,
    satFat: 0.1,
    cholesterol: 0,
    sodium: 2,
    fibre: 4.4,
    sugars: 19.0,
    vitaminA: 98,
    vitaminC: 8.4,
    calcium: 11,
    iron: 0.2,
    potassium: 195,
  },
  {
    id: "cucumber_salad",
    name: "Cucumber & Tomato Salad",
    category: "Fruits & Veggies",
    calories: 45,
    unit: "bowl (150 g)",
    grams: 150,
    carbs: 9.0,
    fat: 0.5,
    protein: 1.8,
    satFat: 0.1,
    cholesterol: 0,
    sodium: 35,
    fibre: 2.2,
    sugars: 5.0,
    vitaminA: 620,
    vitaminC: 22.0,
    calcium: 28,
    iron: 0.8,
    potassium: 290,
  },

  // ─── SNACKS & FAST FOOD ───
  {
    id: "samosa",
    name: "Samosa",
    category: "Snacks & Fast Food",
    calories: 260,
    unit: "1 piece (90 g)",
    grams: 90,
    carbs: 32.0,
    fat: 14.0,
    protein: 4.5,
    satFat: 3.8,
    cholesterol: 0,
    sodium: 380,
    fibre: 2.4,
    sugars: 1.2,
    vitaminA: 20,
    vitaminC: 6.0,
    calcium: 20,
    iron: 1.5,
    potassium: 180,
  },
  {
    id: "veg_sandwich",
    name: "Grilled Veg Sandwich",
    category: "Snacks & Fast Food",
    calories: 220,
    unit: "serving (160 g)",
    grams: 160,
    carbs: 34.0,
    fat: 7.2,
    protein: 5.8,
    satFat: 2.1,
    cholesterol: 8,
    sodium: 440,
    fibre: 3.5,
    sugars: 4.2,
    vitaminA: 180,
    vitaminC: 14.0,
    calcium: 85,
    iron: 2.0,
    potassium: 240,
  },

  // ─── BEVERAGES ───
  {
    id: "chai_tea",
    name: "Masala Chai with Milk & Sugar",
    category: "Beverages",
    calories: 90,
    unit: "cup (150 ml)",
    grams: 150,
    carbs: 14.0,
    fat: 2.8,
    protein: 2.5,
    satFat: 1.8,
    cholesterol: 8,
    sodium: 40,
    fibre: 0,
    sugars: 12.5,
    vitaminA: 40,
    vitaminC: 0.5,
    calcium: 85,
    iron: 0.2,
    potassium: 95,
  },
  {
    id: "filter_coffee",
    name: "South Indian Filter Coffee",
    category: "Beverages",
    calories: 105,
    unit: "cup (150 ml)",
    grams: 150,
    carbs: 15.0,
    fat: 3.2,
    protein: 2.8,
    satFat: 2.0,
    cholesterol: 10,
    sodium: 45,
    fibre: 0,
    sugars: 13.0,
    vitaminA: 45,
    vitaminC: 0,
    calcium: 95,
    iron: 0.1,
    potassium: 120,
  },
  {
    id: "tender_coconut_water",
    name: "Tender Coconut Water",
    category: "Beverages",
    calories: 46,
    unit: "glass (240 ml)",
    grams: 240,
    carbs: 8.9,
    fat: 0.5,
    protein: 1.7,
    satFat: 0.4,
    cholesterol: 0,
    sodium: 252,
    fibre: 2.6,
    sugars: 6.3,
    vitaminA: 0,
    vitaminC: 5.8,
    calcium: 58,
    iron: 0.7,
    potassium: 600,
  },
  {
    id: "whey_protein_shake",
    name: "Whey Protein Shake (with water)",
    category: "High Protein",
    calories: 130,
    unit: "1 scoop (32 g)",
    grams: 32,
    carbs: 3.0,
    fat: 1.5,
    protein: 25.0,
    satFat: 0.8,
    cholesterol: 45,
    sodium: 140,
    fibre: 0.5,
    sugars: 1.5,
    vitaminA: 0,
    vitaminC: 0,
    calcium: 130,
    iron: 0.8,
    potassium: 160,
  },
];

/**
 * Filter and search foods by search query and category
 */
export function searchFoodDatabase(
  query: string = "",
  category: FoodCategory = "All"
): FoodDefinition[] {
  const cleanQ = query.trim().toLowerCase();
  return FOOD_DATABASE.filter((item) => {
    const matchesCategory =
      category === "All" ||
      item.category === category ||
      (category === "Breakfast" && ["South Indian", "Breakfast", "Dairy & Eggs"].includes(item.category));
    const matchesQuery =
      cleanQ.length === 0 ||
      item.name.toLowerCase().includes(cleanQ) ||
      item.category.toLowerCase().includes(cleanQ) ||
      (item.brand && item.brand.toLowerCase().includes(cleanQ));
    return matchesCategory && matchesQuery;
  });
}

/**
 * Fallback to Open Food Facts free public API for barcode or rare foods
 */
export async function searchOpenFoodFacts(query: string): Promise<FoodDefinition[]> {
  try {
    const trimmed = query.trim();
    if (!trimmed || trimmed.length < 2) return [];

    const url = `https://world.openfoodfacts.org/cgi/search.pl?search_terms=${encodeURIComponent(
      trimmed
    )}&search_simple=1&action=process&json=1&page_size=8`;

    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 4500);

    const res = await fetch(url, { signal: controller.signal });
    clearTimeout(timeoutId);

    if (!res.ok) return [];
    const data = await res.json();
    if (!data.products || !Array.isArray(data.products)) return [];

    return data.products
      .filter((p: any) => p.product_name && p.nutriments)
      .map((p: any) => {
        const nut = p.nutriments || {};
        const cal = Math.round(nut["energy-kcal_100g"] || nut["energy-kcal"] || 0);
        return {
          id: `off_${p.code || Math.random().toString(36).substring(2, 8)}`,
          name: p.product_name,
          category: "All" as FoodCategory,
          brand: p.brands || undefined,
          calories: cal,
          unit: "serving (100 g)",
          grams: 100,
          carbs: Math.round((nut.carbohydrates_100g || 0) * 10) / 10,
          fat: Math.round((nut.fat_100g || 0) * 10) / 10,
          protein: Math.round((nut.proteins_100g || 0) * 10) / 10,
          satFat: Math.round((nut["saturated-fat_100g"] || 0) * 10) / 10,
          cholesterol: Math.round((nut.cholesterol_100g || 0) * 1000),
          sodium: Math.round((nut.sodium_100g || 0) * 1000),
          fibre: Math.round((nut.fiber_100g || 0) * 10) / 10,
          sugars: Math.round((nut.sugars_100g || 0) * 10) / 10,
          vitaminA: 0,
          vitaminC: 0,
          calcium: Math.round((nut.calcium_100g || 0) * 1000),
          iron: Math.round((nut.iron_100g || 0) * 1000),
          potassium: Math.round((nut.potassium_100g || 0) * 1000),
        };
      });
  } catch {
    return [];
  }
}
